openapi: 3.0.1
info:
  title: bp
  description: ''
  version: '1.0'
servers:
  - url: https://apim.pre.dvn.com/bp
  - url: https://api.pre.dvn.com/bp
  - url: https://ext.api.pre.dvn.com/bp
paths:
  '/{action}':
    get:
      summary: 'economic_forecasts,economic_one_line_summary,gross_operated_production'
      description: 'economic_forecasts,economic_one_line_summary,gross_operated_production'
      operationId: wbs-waterfall-type-curve-economic-forecast
      parameters:
        - name: action
          in: path
          required: true
          schema:
            type: ''
      responses:
        '200':
          description: 'null'
  /pro_drill_results:
    get:
      summary: pro_drill_results
      description: pro_drill_results
      operationId: pro-drill-results
      responses:
        '200':
          description: 'null'
components: { }