openapi: 3.0.1
info:
  title: completions
  description: ''
  version: '1.0'
servers:
  - url: https://apim.pre.dvn.com/completions
  - url: https://api.pre.dvn.com/completions
  - url: https://ext.api.pre.dvn.com/completions
paths:
  '/{action}':
    get:
      summary: completions
      description: completions
      operationId: completions
      parameters:
        - name: action
          in: path
          required: true
          schema:
            type: ''
      responses:
        '200':
          description: 'null'
  /pi_completions_events_flattime:
    get:
      summary: pi_completions
      description: pi_completions
      operationId: pi-completions
      responses:
        '200':
          description: 'null'
  /pi_completions_events_pumping:
    get:
      summary: pi_completions_events_pumping
      description: pi_completions_events_pumping
      operationId: pi-completions-events-pumping
      responses:
        '200':
          description: 'null'
components: { }