openapi: 3.0.1
info:
  title: SAP LDAR
  description: SAP LDAR API
  version: '1.0'
servers:
  - url: https://apim.pre.dvn.com/dsc/ldar
  - url: https://api.pre.dvn.com/dsc/ldar
  - url: https://ext.api.pre.dvn.com/dsc/ldar
paths:
  '/{action}':
    put:
      summary: PUT
      description: PUT
      operationId: put
      parameters:
        - name: action
          in: path
          required: true
          schema:
            type: ''
      responses:
        '200':
          description: 'null'
    post:
      summary: POST
      description: POST
      operationId: post
      parameters:
        - name: action
          in: path
          required: true
          schema:
            type: ''
      responses:
        '200':
          description: 'null'
    get:
      summary: Returns GET data.
      description: "Returns GET data.\n"
      operationId: get
      parameters:
        - name: action
          in: path
          required: true
          schema:
            type: ''
      responses:
        '200':
          description: 'null'
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]