openapi: 3.0.1
info:
  title: Enterprise Notification Services
  description: API for sending email and sms messages.
  version: '1.0'
servers:
  - url: https://apim.pre.dvn.com/ens
  - url: https://api.pre.dvn.com/ens
  - url: https://ext.api.pre.dvn.com/ens
paths:
  /Sms:
    post:
      tags:
        - Sms
      summary: Sms
      description: This sends an sms message.
      operationId: Sms
      requestBody:
        description: The sms request
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/smsRequest'
            example:
              fromPhoneNumber: string
              messageBody: string
              toPhoneNumber: string
      responses:
        '200':
          description: Successful response has no body.
          content:
            text/plain: { }
        '400':
          description: Invalid request body.
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/SmsPost400TextPlainResponse'
              example: ''
        '500':
          description: Internal error processing request.
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/SmsPost500TextPlainResponse'
              example: ''
  /Email:
    post:
      tags:
        - Email
      summary: Email
      description: This sends an email message.
      operationId: Email
      requestBody:
        description: The email request
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/emailRequest'
            example:
              bccAddresses:
                - string
              ccAddresses:
                - string
              fromAddress: string
              isHtml: true
              messageBody: string
              messageSubject: string
              toAddresses:
                - string
      responses:
        '200':
          description: Successful response has no body.
          content:
            text/plain: { }
        '400':
          description: Invalid request body.
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/EmailPost400TextPlainResponse'
              example: ''
        '500':
          description: Internal error processing request.
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/EmailPost500TextPlainResponse'
              example: ''
components:
  schemas:
    emailRequest:
      type: object
      properties:
        bccAddresses:
          type: array
          items:
            type: string
        ccAddresses:
          type: array
          items:
            type: string
        fromAddress:
          type: string
        isHtml:
          type: boolean
        messageBody:
          type: string
        messageSubject:
          type: string
        toAddresses:
          type: array
          items:
            type: string
    smsRequest:
      type: object
      properties:
        fromPhoneNumber:
          type: string
        messageBody:
          type: string
        toPhoneNumber:
          type: string
    SmsPost400TextPlainResponse:
      type: string
    SmsPost500TextPlainResponse:
      type: string
    EmailPost400TextPlainResponse:
      type: string
    EmailPost500TextPlainResponse:
      type: string
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]