openapi: 3.0.1
info:
  title: aprec
  description: ''
  version: '1.0'
servers:
  - url: https://apim.pre.dvn.com/aprec
  - url: https://api.pre.dvn.com/aprec
  - url: https://ext.api.pre.dvn.com/aprec
paths:
  '/{action}':
    get:
      summary: stale_invoice_summary and invoice_status_summary
      description: stale_invoice_summary and invoice_status_summary
      operationId: stale-invoice-summary
      parameters:
        - name: action
          in: path
          required: true
          schema:
            type: ''
      responses:
        '200':
          description: 'null'
components: { }